groups:
  - name: ParseFinAlerts
    rules:
      - alert: HighErrorRate
        expr: |
          100 * (
            sum(rate(parsefin_http_requests_total{status=~"5.."}[5m]))
            /
            sum(rate(parsefin_http_requests_total[5m]))
          ) > 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High Error Rate detected"
          description: "Error rate is above 5% for the last 5 minutes."

      - alert: SlowResponse
        expr: histogram_quantile(0.95, sum(rate(parsefin_http_request_duration_seconds_bucket[5m])) by (le)) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow Response Time"
          description: "P95 latency is above 2 seconds."
